/*
 * Copyright 2026 Roberto Leinardi.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package generate_test

import (
	"bytes"
	"errors"
	"go/format"
	"strings"
	"testing"

	"github.com/leinardi/monmux/internal/catalog/internal/generate"
)

// entry is one well-formed catalog entry, and valid is the smallest catalog file
// that satisfies every rule. The rejection table below breaks exactly one thing
// in it at a time; the two-model cases append a second copy of entry.
const entry = `  - name: TEST-1
    vendor: ACME
    identities:
      - manufacturer: ACM
        product_code: 0x0001
    write_enabled: true
    inputs:
      dp:
        mechanism: lg-alt-input
        value: 0xD0
        evidence: switched on the unit
    sources:
      - a named source
`

const valid = "models:\n" + entry

func TestTheSmallestValidCatalogRenders(t *testing.T) {
	t.Parallel()

	rendered, err := generate.Generate([]byte(valid))
	if err != nil {
		t.Fatalf("a valid catalog was rejected: %v", err)
	}

	for _, want := range []string{
		"// Code generated by internal/catalog/internal/generate from models.yaml; DO NOT EDIT.",
		"package catalog",
		"var models = []Model{",
		`Name:   "TEST-1"`,
		`{Manufacturer: "ACM", ProductCode: 0x0001},`,
		"WriteEnabled: true,",
		`"dp": {`,
		"mechanism: MechanismLGAltInput,",
		"value:     0xD0,",
		`evidence:  "switched on the unit",`,
	} {
		if !strings.Contains(string(rendered), want) {
			t.Errorf("the rendered catalog does not contain %q", want)
		}
	}
}

// Every rule the generator enforces, and the file that breaks it. A rule that
// stops being enforced fails a row here rather than being noticed on hardware.
func TestInvalidCatalogsAreRejected(t *testing.T) {
	t.Parallel()

	cases := map[string]struct {
		document string
		want     error
	}{
		"unknown key": {
			document: strings.Replace(
				valid,
				"    vendor: ACME",
				"    vendor: ACME\n    color: black",
				1,
			),
			want: generate.ErrMalformed,
		},
		"a value wider than a byte": {
			document: strings.Replace(valid, "value: 0xD0", "value: 0x100", 1),
			want:     generate.ErrMalformed,
		},
		"a product code wider than two bytes": {
			document: strings.Replace(valid, "product_code: 0x0001", "product_code: 0x10000", 1),
			want:     generate.ErrMalformed,
		},
		"a negative value": {
			document: strings.Replace(valid, "value: 0xD0", "value: -1", 1),
			want:     generate.ErrMalformed,
		},
		"no models at all": {
			document: "models: []\n",
			want:     generate.ErrEmptyCatalog,
		},
		"an empty name": {
			document: strings.Replace(valid, "name: TEST-1", `name: ""`, 1),
			want:     generate.ErrBlank,
		},
		"a whitespace-only name": {
			document: strings.Replace(valid, "name: TEST-1", `name: "   "`, 1),
			want:     generate.ErrBlank,
		},
		"an empty vendor": {
			document: strings.Replace(valid, "vendor: ACME", `vendor: ""`, 1),
			want:     generate.ErrBlank,
		},
		"a whitespace-only vendor": {
			document: strings.Replace(valid, "vendor: ACME", `vendor: "  "`, 1),
			want:     generate.ErrBlank,
		},
		"an empty evidence": {
			document: strings.Replace(valid, "evidence: switched on the unit", `evidence: ""`, 1),
			want:     generate.ErrBlank,
		},
		"a whitespace-only evidence": {
			document: strings.Replace(valid, "evidence: switched on the unit", `evidence: "  "`, 1),
			want:     generate.ErrBlank,
		},
		"an empty source": {
			document: strings.Replace(valid, "- a named source", `- ""`, 1),
			want:     generate.ErrBlank,
		},
		"a whitespace-only source": {
			document: strings.Replace(valid, "- a named source", `- "  "`, 1),
			want:     generate.ErrBlank,
		},
		"write-enabled with no identity": {
			document: strings.Replace(valid,
				"    identities:\n      - manufacturer: ACM\n        product_code: 0x0001",
				"    identities: []", 1),
			want: generate.ErrIdentityRequired,
		},
		"not write-enabled but carrying an identity": {
			document: strings.Replace(valid, "write_enabled: true", "write_enabled: false", 1),
			want:     generate.ErrIdentityForbidden,
		},
		"no inputs": {
			document: strings.Replace(valid,
				"    inputs:\n      dp:\n        mechanism: lg-alt-input\n"+
					"        value: 0xD0\n        evidence: switched on the unit",
				"    inputs: {}", 1),
			want: generate.ErrNoInputs,
		},
		"no sources": {
			document: strings.Replace(
				valid,
				"    sources:\n      - a named source",
				"    sources: []",
				1,
			),
			want: generate.ErrNoSources,
		},
		"an input of an unknown kind": {
			document: strings.Replace(valid, "      dp:", "      scart:", 1),
			want:     generate.ErrUnknownInput,
		},
		"a port number with a leading zero": {
			document: strings.Replace(valid, "      dp:", "      hdmi01:", 1),
			want:     generate.ErrUnknownInput,
		},
		"a port number of zero": {
			document: strings.Replace(valid, "      dp:", "      hdmi0:", 1),
			want:     generate.ErrUnknownInput,
		},
		"a bare and a numbered port of one kind": {
			document: strings.Replace(
				valid,
				"      dp:\n",
				"      usb-c:\n        mechanism: lg-alt-input\n        value: 0xD1\n"+
					"        evidence: switched on the unit\n      usb-c2:\n",
				1,
			),
			want: generate.ErrMixedNumbering,
		},
		"a mechanism no backend implements": {
			document: strings.Replace(valid, "mechanism: lg-alt-input", "mechanism: vcp-60", 1),
			want:     generate.ErrUnknownMechanism,
		},
		"a lowercase manufacturer": {
			document: strings.Replace(valid, "manufacturer: ACM", "manufacturer: acm", 1),
			want:     generate.ErrManufacturer,
		},
		"a manufacturer of the wrong length": {
			document: strings.Replace(valid, "manufacturer: ACM", "manufacturer: ACME", 1),
			want:     generate.ErrManufacturer,
		},
		"two models with the same name": {
			document: valid + strings.Replace(
				entry,
				"product_code: 0x0001",
				"product_code: 0x0002",
				1,
			),
			want: generate.ErrDuplicateModel,
		},
		"a product code that was never written": {
			document: strings.Replace(valid, "        product_code: 0x0001\n", "", 1),
			want:     generate.ErrMissing,
		},
		"a null product code": {
			document: strings.Replace(valid, "product_code: 0x0001", "product_code: null", 1),
			want:     generate.ErrMissing,
		},
		"a value that was never written": {
			document: strings.Replace(valid, "        value: 0xD0\n", "", 1),
			want:     generate.ErrMissing,
		},
		"a null value": {
			document: strings.Replace(valid, "value: 0xD0", "value: null", 1),
			want:     generate.ErrMissing,
		},
		"a second YAML document": {
			document: valid + "---\n" + entry,
			want:     generate.ErrMalformed,
		},
		"a second YAML document hidden behind an empty one": {
			document: valid + "---\n---\n" + entry,
			want:     generate.ErrMalformed,
		},
		"a malformed second YAML document": {
			document: valid + "---\nmodels: [oh dear\n",
			want:     generate.ErrMalformed,
		},
		"two models claiming one identity": {
			document: valid + strings.Replace(entry, "name: TEST-1", "name: TEST-2", 1),
			want:     generate.ErrDuplicateIdentity,
		},
	}

	for name, testCase := range cases {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			_, err := generate.Generate([]byte(testCase.document))
			if err == nil {
				t.Fatalf("%s was accepted", name)
			}

			if !errors.Is(err, testCase.want) {
				t.Errorf("%s gave %v, want %v", name, err, testCase.want)
			}
		})
	}
}

// A YAML stream may open and close with a document marker. Rejecting a second
// document must not reject a file that simply writes the first one out in full.
func TestDocumentMarkersAroundOneDocumentAreFine(t *testing.T) {
	t.Parallel()

	for name, document := range map[string]string{
		"a leading marker":                "---\n" + valid,
		"a trailing marker":               valid + "---\n",
		"both":                            "---\n" + valid + "---\n",
		"an empty document in the middle": valid + "---\n---\n",
	} {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			_, err := generate.Generate([]byte(document))
			if err != nil {
				t.Errorf("%s was rejected: %v", name, err)
			}
		})
	}
}

// Render reads the product code and the value through pointers, and validation
// is what guarantees they are set. This is the test that the guarantee holds: a
// document missing either must come back as an error, never as a panic and never
// as a rendered zero byte.
func TestRenderRefusesADocumentItCannotTrust(t *testing.T) {
	t.Parallel()

	document := generate.Document{
		Models: []generate.Model{
			{
				Name:         "TEST-1",
				Vendor:       "ACME",
				Identities:   []generate.Identity{{Manufacturer: "ACM", ProductCode: nil}},
				WriteEnabled: true,
				Inputs: map[string]generate.Input{
					"dp": {Mechanism: "lg-alt-input", Value: nil, Evidence: "tested"},
				},
				Sources: []string{"a named source"},
			},
		},
	}

	rendered, err := generate.Render(document)
	if err == nil {
		t.Fatalf("Render accepted a document with no product code and no value:\n%s", rendered)
	}

	if !errors.Is(err, generate.ErrMissing) {
		t.Errorf("Render gave %v, want %v", err, generate.ErrMissing)
	}
}

// The rendered file must not depend on the order the keys happen to have in the
// catalog file, or an unrelated edit would show up as a diff of the bytes sent
// to a monitor.
func TestInputsRenderInCatalogOrderWhateverTheFileSays(t *testing.T) {
	t.Parallel()

	document := `
models:
  - name: TEST-1
    vendor: ACME
    identities:
      - manufacturer: ACM
        product_code: 0x0001
    write_enabled: true
    inputs:
      hdmi2:
        mechanism: lg-alt-input
        value: 0x91
        evidence: tested
      dp:
        mechanism: lg-alt-input
        value: 0xD0
        evidence: tested
      hdmi1:
        mechanism: lg-alt-input
        value: 0x90
        evidence: tested
      hdmi10:
        mechanism: lg-alt-input
        value: 0x99
        evidence: tested
      usb-c:
        mechanism: lg-alt-input
        value: 0xD1
        evidence: tested
    sources:
      - a named source
`

	rendered, err := generate.Generate([]byte(document))
	if err != nil {
		t.Fatalf("rendering: %v", err)
	}

	order := []string{`"dp":`, `"hdmi1":`, `"hdmi2":`, `"hdmi10":`, `"usb-c":`}

	previous := -1

	for _, name := range order {
		at := bytes.Index(rendered, []byte(name))
		if at < 0 {
			t.Fatalf("%s is missing from the rendered catalog", name)
		}

		if at < previous {
			t.Errorf("%s is rendered out of catalog order", name)
		}

		previous = at
	}
}

// A model that can never match renders its identities as nil rather than as an
// empty slice, which is what "monmux will never write to this" looks like in Go.
func TestAnUnmatchableModelRendersNilIdentities(t *testing.T) {
	t.Parallel()

	document := `
models:
  - name: TEST-1
    vendor: ACME
    identities: []
    write_enabled: false
    inputs:
      dp:
        mechanism: lg-alt-input
        value: 0xD0
        evidence: reported elsewhere, not verified here
    sources:
      - a named source
`

	rendered, err := generate.Generate([]byte(document))
	if err != nil {
		t.Fatalf("rendering: %v", err)
	}

	if !strings.Contains(string(rendered), "Identities:   nil,") {
		t.Errorf("an entry with no identity did not render as nil:\n%s", rendered)
	}
}

// The generated file is committed, so it has to be formatted the way every other
// file in the repository is, or the formatter would rewrite it and the drift test
// would fail on a clean checkout.
func TestTheRenderedCatalogIsAlreadyFormatted(t *testing.T) {
	t.Parallel()

	rendered, err := generate.Generate([]byte(valid))
	if err != nil {
		t.Fatalf("rendering: %v", err)
	}

	formatted, err := format.Source(rendered)
	if err != nil {
		t.Fatalf("the rendered catalog is not valid Go: %v", err)
	}

	if !bytes.Equal(formatted, rendered) {
		t.Error("the rendered catalog is not gofmt-clean")
	}
}
