/*
 * Copyright 2026 Roberto Leinardi.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package generate

import (
	"errors"
	"fmt"
	"go/format"
	"slices"
	"strings"

	"github.com/leinardi/monmux/internal/catalog/internal/input"
)

// ErrRender reports Go source the formatter rejected, which means this package
// has a bug rather than the catalog file having one.
var ErrRender = errors.New("generate: the rendered catalog is not valid Go")

// licenseHeader is the block every Go file in this repository starts with.
const licenseHeader = `/*
 * Copyright 2026 Roberto Leinardi.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */`

// linesPerInput is how many lines renderInputs emits for one recorded input.
const linesPerInput = 5

// generatedMarker is the line that tells go and the linters this file is not
// written by hand.
const generatedMarker = "// Code generated by internal/catalog/internal/generate from models.yaml; DO NOT EDIT."

// Render validates a document and turns it into the Go source of the catalog.
// The output is gofmt-clean and depends only on the document, so regenerating an
// unchanged file produces an unchanged file.
//
// It validates first rather than trusting the caller: the renderers below read
// the product code and the value through pointers, and [Document.Validate] is
// what guarantees those are not nil. A document that fails validation is never
// rendered, so a byte the file never wrote cannot reach the generated catalog.
func Render(document Document) ([]byte, error) {
	err := document.Validate()
	if err != nil {
		return nil, err
	}

	body := make([]string, 0, len(document.Models))

	for index := range document.Models {
		entry, renderErr := renderModel(&document.Models[index])
		if renderErr != nil {
			return nil, renderErr
		}

		body = append(body, entry...)
	}

	lines := slices.Concat(preamble(), body, []string{"}", ""})

	formatted, err := format.Source([]byte(strings.Join(lines, "\n")))
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrRender, err)
	}

	return formatted, nil
}

// preamble is everything above the first entry: the license, the marker that
// tells the tooling this file is generated, and the declaration the entries go
// into.
func preamble() []string {
	return []string{
		licenseHeader,
		"",
		generatedMarker,
		"",
		"package catalog",
		"",
		"// models is the supported-monitor catalog. It is rendered from models.yaml,",
		"// which is the file to edit; run `make go-generate` afterwards. A test fails",
		"// the build if this file and models.yaml disagree.",
		"var models = []Model{",
	}
}

// renderModel renders one entry of the models slice.
func renderModel(model *Model) ([]string, error) {
	inputs, err := renderInputs(model.Inputs)
	if err != nil {
		return nil, err
	}

	return slices.Concat(
		[]string{
			"{",
			fmt.Sprintf("Name: %q,", model.Name),
			fmt.Sprintf("Vendor: %q,", model.Vendor),
		},
		renderIdentities(model.Identities),
		[]string{fmt.Sprintf("WriteEnabled: %t,", model.WriteEnabled)},
		inputs,
		renderSources(model.Sources),
		[]string{"},"},
	), nil
}

// renderIdentities renders the fingerprints. An entry with none renders as nil,
// which is what an entry monmux can never match looks like in Go.
func renderIdentities(identities []Identity) []string {
	if len(identities) == 0 {
		return []string{"Identities: nil,"}
	}

	lines := make([]string, 0, len(identities)+2)
	lines = append(lines, "Identities: []Identity{")

	for _, identity := range identities {
		lines = append(lines, fmt.Sprintf(
			"{Manufacturer: %q, ProductCode: 0x%04X},",
			identity.Manufacturer,
			*identity.ProductCode,
		))
	}

	return append(lines, "},")
}

// renderInputs renders the input map in catalog order - connector kind, then
// port number - so the generated file does not depend on the order the keys
// happen to have in the catalog file.
//
// A key that does not parse is an error rather than a name sorted at one end:
// [Document.Validate] has already rejected such a document, so reaching here
// means this package has a bug, and a fallback order would not be transitive.
func renderInputs(entries map[string]Input) ([]string, error) {
	names := make([]input.Name, 0, len(entries))

	for name := range entries {
		parsed, err := input.Parse(name)
		if err != nil {
			return nil, fmt.Errorf("%w: %q: %w", ErrRender, name, err)
		}

		names = append(names, parsed)
	}

	slices.SortFunc(names, input.Compare)

	lines := make([]string, 0, len(entries)*linesPerInput+2)
	lines = append(lines, "Inputs: map[Input]inputOp{")

	for _, name := range names {
		entry := entries[name.String()]

		lines = append(lines,
			fmt.Sprintf("%q: {", name.String()),
			fmt.Sprintf("mechanism: %s,", mechanismNames[entry.Mechanism]),
			fmt.Sprintf("value: 0x%02X,", *entry.Value),
			fmt.Sprintf("evidence: %q,", entry.Evidence),
			"},",
		)
	}

	return append(lines, "},"), nil
}

// renderSources renders the model-level references.
func renderSources(sources []string) []string {
	if len(sources) == 0 {
		return []string{"Sources: nil,"}
	}

	lines := make([]string, 0, len(sources)+2)
	lines = append(lines, "Sources: []string{")

	for _, source := range sources {
		lines = append(lines, fmt.Sprintf("%q,", source))
	}

	return append(lines, "},")
}
