/*
 * Copyright 2026 Roberto Leinardi.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package generate

import (
	"errors"
	"fmt"
	"go/format"
	"slices"
	"strings"

	"github.com/leinardi/monmux/internal/catalog/internal/input"
)

// ErrRender reports Go source the formatter rejected, which means this package
// has a bug rather than the catalog file having one.
var ErrRender = errors.New("generate: the rendered catalog is not valid Go")

// licenseHeader is the block every Go file in this repository starts with.
const licenseHeader = `/*
 * Copyright 2026 Roberto Leinardi.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */`

// linesPerInput is how many lines renderInputs emits for one recorded input.
const linesPerInput = 6

// generatedMarker is the line that tells go and the linters this file is not
// written by hand.
const generatedMarker = "// Code generated by internal/catalog/internal/generate from models.yaml; DO NOT EDIT."

// Render validates a document and turns it into the Go source of the catalog.
// The output is gofmt-clean and depends only on the document, so regenerating an
// unchanged file produces an unchanged file.
//
// It validates first rather than trusting the caller: the renderers below read
// the product code and the value through pointers, and [Document.Validate] is
// what guarantees those are not nil. A document that fails validation is never
// rendered, so a byte the file never wrote cannot reach the generated catalog.
func Render(document Document) ([]byte, error) {
	err := document.Validate()
	if err != nil {
		return nil, err
	}

	body := make([]string, 0, len(document.Models))

	for index := range document.Models {
		entry, renderErr := renderModel(&document.Models[index])
		if renderErr != nil {
			return nil, renderErr
		}

		body = append(body, entry...)
	}

	lines := slices.Concat(preamble(), body, []string{"}", ""})

	formatted, err := format.Source([]byte(strings.Join(lines, "\n")))
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrRender, err)
	}

	return formatted, nil
}

// preamble is everything above the first entry: the license, the marker that
// tells the tooling this file is generated, and the declaration the entries go
// into.
func preamble() []string {
	return []string{
		licenseHeader,
		"",
		generatedMarker,
		"",
		"package catalog",
		"",
		"// models is the supported-monitor catalog. It is rendered from models.yaml,",
		"// which is the file to edit; run `make go-generate` afterwards. A test fails",
		"// the build if this file and models.yaml disagree.",
		"var models = []Model{",
	}
}

// renderModel renders one entry of the models slice.
func renderModel(model *Model) ([]string, error) {
	inputs, err := renderInputs(model)
	if err != nil {
		return nil, err
	}

	return slices.Concat(
		[]string{
			"{",
			fmt.Sprintf("Name: %q,", model.Name),
			fmt.Sprintf("Vendor: %q,", model.Vendor),
		},
		renderIdentities(model.Identities),
		[]string{fmt.Sprintf("WriteEnabled: %t,", model.WriteEnabled)},
		inputs,
		renderStrings("Notes", model.Notes),
		renderStrings("Sources", model.Sources),
		[]string{"},"},
	), nil
}

// renderIdentities renders the fingerprints. An entry with none renders as nil,
// which is what an entry monmux can never match looks like in Go.
func renderIdentities(identities []Identity) []string {
	if len(identities) == 0 {
		return []string{"Identities: nil,"}
	}

	lines := make([]string, 0, len(identities)+2)
	lines = append(lines, "Identities: []Identity{")

	for _, identity := range identities {
		rendered := fmt.Sprintf(
			"{Manufacturer: %q, ProductCode: 0x%04X",
			identity.Manufacturer,
			*identity.ProductCode,
		)

		// An unpinned name renders as nothing rather than as an empty string, so
		// that "this identity matches on the code alone" is what the Go says.
		if identity.ModelName != "" {
			rendered += fmt.Sprintf(", ModelName: %q", identity.ModelName)
		}

		lines = append(lines, rendered+"},")
	}

	return append(lines, "},")
}

// renderInputs renders the input map in the order [sortedInputNames] decides,
// so the generated file does not depend on the order the keys happen to have in
// the catalog file.
func renderInputs(model *Model) ([]string, error) {
	entries := model.Inputs

	names, err := sortedInputNames(model)
	if err != nil {
		return nil, err
	}

	lines := make([]string, 0, len(entries)*linesPerInput+2)
	lines = append(lines, "Inputs: map[Input]inputOp{")

	for _, name := range names {
		entry := entries[name.String()]

		evidence, evidenceErr := renderEvidence(model.Name, name, &entry)
		if evidenceErr != nil {
			return nil, evidenceErr
		}

		lines = append(lines,
			fmt.Sprintf("%q: {", name.String()),
			fmt.Sprintf("mechanism: %s,", mechanismNames[entry.Mechanism]),
			fmt.Sprintf("value: 0x%02X,", *entry.Value),
			fmt.Sprintf("grade: %s,", gradeNames[entry.Evidence.Grade]),
			fmt.Sprintf("evidence: %q,", evidence),
			"},",
		)
	}

	return append(lines, "},"), nil
}

// sortedInputNames parses a model's input keys and puts them in catalog order -
// connector kind, then port number - so neither the generated Go nor the
// generated documentation depends on the order the keys happen to have in the
// catalog file. Both renderers sort through this one function, which is what
// makes a row of the table line up with an entry of the map.
//
// A key that does not parse is an error rather than a name sorted at one end:
// [Document.Validate] has already rejected such a document, so reaching here
// means this package has a bug, and a fallback order would not be transitive.
func sortedInputNames(model *Model) ([]input.Name, error) {
	names := make([]input.Name, 0, len(model.Inputs))

	for name := range model.Inputs {
		parsed, err := input.Parse(name)
		if err != nil {
			return nil, fmt.Errorf("%w: %q: %w", ErrRender, name, err)
		}

		names = append(names, parsed)
	}

	slices.SortFunc(names, input.Compare)

	return names, nil
}

// renderEvidence composes the sentence the catalog and the documentation both
// carry, from the fields the catalog file records. One grade always reads the
// same way, so the strength of a claim is legible at a glance and cannot be
// talked up in prose: what a row says is decided by its grade, not by whoever
// wrote it.
//
// [Document.Validate] has already checked the grade and the fields it needs, so
// an error here means this package has a bug rather than the file having one.
func renderEvidence(model string, name input.Name, entry *Input) (string, error) {
	evidence := &entry.Evidence

	phrase, known := mechanismPhrases[entry.Mechanism]
	if !known {
		return "", fmt.Errorf("%w: no phrase for mechanism %q", ErrRender, entry.Mechanism)
	}

	var (
		label = name.Label()
		value = fmt.Sprintf("0x%02X", *entry.Value)
		body  string
	)

	switch evidence.Grade {
	case gradeVerified:
		// A verified row is the only one that describes an act rather than a
		// claim, so it names what was switched and needs no "not verified here".
		return fmt.Sprintf(
			"Direct test on the unit, %s, %s: %s", evidence.Date, evidence.Tool, evidence.Note,
		), nil
	case gradeDocumented:
		body = fmt.Sprintf(
			"Documented by %s for the exact %s: %s is %s over %s; no field report",
			evidence.By, model, label, value, phrase,
		)
	case gradeReported:
		body = fmt.Sprintf(
			"Reported working on the exact %s by %s (%s): switching to %s with %s over %s succeeded",
			model,
			evidence.By,
			evidence.Tool,
			label,
			value,
			phrase,
		)
	case gradeQuoted:
		body = fmt.Sprintf(
			"Weaker report on the exact %s by %s (%s): the report quotes %s for %s and says it "+
				"works, without saying which inputs were tried individually",
			model, evidence.By, evidence.Tool, value, label,
		)
	default:
		return "", fmt.Errorf("%w: unknown grade %q", ErrRender, evidence.Grade)
	}

	if evidence.Note != "" {
		body += "; " + evidence.Note
	}

	return body + "; not verified here: " + evidence.URL, nil
}

// renderStrings renders a model's string slice - its notes or its sources. An
// empty one renders as nil rather than as an empty slice, which is what "this
// entry records none" looks like in Go.
func renderStrings(field string, values []string) []string {
	if len(values) == 0 {
		return []string{field + ": nil,"}
	}

	lines := make([]string, 0, len(values)+2)
	lines = append(lines, field+": []string{")

	for _, value := range values {
		lines = append(lines, fmt.Sprintf("%q,", value))
	}

	return append(lines, "},")
}
