/*
 * Copyright 2026 Roberto Leinardi.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by internal/catalog/internal/generate from models.yaml; DO NOT EDIT.

package catalog

// models is the supported-monitor catalog. It is rendered from models.yaml,
// which is the file to edit; run `make go-generate` afterwards. A test fails
// the build if this file and models.yaml disagree.
var models = []Model{
	{
		Name:   "38WR85QC-W",
		Vendor: "LG",
		Identities: []Identity{
			{Manufacturer: "GSM", ProductCode: 0x77D3},
			{Manufacturer: "GSM", ProductCode: 0x77D4},
		},
		WriteEnabled: true,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeVerified,
				evidence:  "Direct test on the unit, 2026-09-07, Linux (ddcutil) and macOS (m1ddc): switched from USB-C to DisplayPort",
			},
			"usb-c": {
				mechanism: MechanismLGAltInput,
				value:     0xD1,
				grade:     GradeVerified,
				evidence:  "Direct test on the unit, 2026-09-07, Linux (ddcutil) and macOS (m1ddc): switched from DisplayPort to USB-C",
			},
		},
		Notes: []string{
			"Two identities, because the same physical unit reports `GSM/0x77D3` while displaying DisplayPort and `GSM/0x77D4` while displaying USB-C. Both were observed directly; the model string is `LG ULTRAWIDE`, which is not used for matching.",
			"`hdmi1` and `hdmi2` are deliberately absent rather than disabled. The values were never tested on this unit, and another LG model using them is not evidence for this one. Asking for them is refused with `input-not-enabled`. Several sources say the HDMI inputs of a 38WR85QC-W respond to `0x90` and `0x91`; because this model is write-enabled, recording them would enable a write, so they stay out until somebody runs them on this unit by hand, the way [testing.md](testing.md) describes.",
		},
		Sources: []string{
			"Direct observation on the tested unit: EDID GSM/0x77D3 (DisplayPort) and GSM/0x77D4 (USB-C), model string LG ULTRAWIDE",
			"https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
		},
	},
	{
		Name:         "38BR85QC",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 38BR85QC by a tester on the ddcutil LG wiki page (ddcutil): switching to DisplayPort with 0xD0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"hdmi1": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 38BR85QC by a tester on the ddcutil LG wiki page (ddcutil): switching to HDMI 1 with 0x90 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"hdmi2": {
				mechanism: MechanismLGAltInput,
				value:     0x91,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 38BR85QC by a tester on the ddcutil LG wiki page (ddcutil): switching to HDMI 2 with 0x91 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"usb-c": {
				mechanism: MechanismLGAltInput,
				value:     0xD1,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 38BR85QC by a tester on the ddcutil LG wiki page (ddcutil): switching to USB-C with 0xD1 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
		},
		Notes: []string{
			"Recorded, disabled, and unable to match anything: no EDID fingerprint for it has been collected. The values come from the ddcutil wiki and nobody involved in this project has a unit to test them on. They are written down because they are useful to a contributor who does — see the contributor guide for what turns a row like this into an enabled one.",
		},
		Sources: []string{
			"https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
		},
	},
	{
		Name:         "27BN88Q-B",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 27BN88Q-B by bansheerubber (ddcutil): switching to DisplayPort with 0xD0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1646752889",
			},
			"hdmi1": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 27BN88Q-B by bansheerubber (ddcutil): switching to HDMI 1 with 0x90 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1646752889",
			},
		},
		Notes: []string{
			"Listed on the ddcutil LG wiki page by bansheerubber, who also wrote the values out in ddcutil issue #100: \"successfully switching between HDMI 1 (0x90) and display port 1 (0xD0)\". Only those two inputs are recorded; no report covers the others.",
		},
		Sources: []string{
			"https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			"https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1646752889",
		},
	},
	{
		Name:         "27UK500-B",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 27UK500-B by francis36012 (ddcutil): switching to DisplayPort with 0xD0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"hdmi1": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 27UK500-B by francis36012 (ddcutil): switching to HDMI 1 with 0x90 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"hdmi2": {
				mechanism: MechanismLGAltInput,
				value:     0x91,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 27UK500-B by francis36012 (ddcutil): switching to HDMI 2 with 0x91 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
		},
		Notes: []string{
			"Test result contributed by francis36012 to the ddcutil LG wiki page. No EDID fingerprint was published with it.",
		},
		Sources: []string{
			"https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
		},
	},
	{
		Name:         "27UL550-W",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 27UL550-W by titou10titou10 (ddcutil): switching to DisplayPort with 0xD0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"hdmi1": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 27UL550-W by titou10titou10 (ddcutil): switching to HDMI 1 with 0x90 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"hdmi2": {
				mechanism: MechanismLGAltInput,
				value:     0x91,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 27UL550-W by titou10titou10 (ddcutil): switching to HDMI 2 with 0x91 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
		},
		Notes: []string{
			"Test result contributed by titou10titou10 to the ddcutil LG wiki page.",
		},
		Sources: []string{
			"https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
		},
	},
	{
		Name:         "27UN850-WY",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 27UN850-WY by ccrxf (ddcutil): switching to DisplayPort with 0xD0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"hdmi1": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 27UN850-WY by ccrxf (ddcutil): switching to HDMI 1 with 0x90 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"hdmi2": {
				mechanism: MechanismLGAltInput,
				value:     0x91,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 27UN850-WY by ccrxf (ddcutil): switching to HDMI 2 with 0x91 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"usb-c": {
				mechanism: MechanismLGAltInput,
				value:     0xD1,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 27UN850-WY by ccrxf (ddcutil): switching to USB-C with 0xD1 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
		},
		Notes: []string{
			"Test result contributed by ccrxf to the ddcutil LG wiki page. The name is kept exactly as the source writes it and is not merged with the separate 27UN850-W entry below, which comes from a different report.",
		},
		Sources: []string{
			"https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
		},
	},
	{
		Name:         "27UN850-W",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 27UN850-W by the tester who added it to the ddcutil LG wiki page (ddcutil): switching to DisplayPort with 0xD0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; the report switched from the USB-C input; the wiki row records the model as confirmed without values, which that tester quotes in the linked comment; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1627345011",
			},
			"hdmi1": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 27UN850-W by the tester who added it to the ddcutil LG wiki page (ddcutil): switching to HDMI 1 with 0x90 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; the report switched from the USB-C input; the wiki row records the model as confirmed without values, which that tester quotes in the linked comment; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1627345011",
			},
			"hdmi2": {
				mechanism: MechanismLGAltInput,
				value:     0x91,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 27UN850-W by the tester who added it to the ddcutil LG wiki page (ddcutil): switching to HDMI 2 with 0x91 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; the report switched from the USB-C input; the wiki row records the model as confirmed without values, which that tester quotes in the linked comment; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1627345011",
			},
		},
		Notes: []string{
			"The wiki row says \"confirmed\" and gives no values. The values come from the same tester's comment on ddcutil issue #100, which reports switching from the USB-C input to the HDMI1, HDMI2 and DP1 inputs with x0090, x0091 and x00d0. USB-C is not recorded: the report switches away from it, never to it.",
		},
		Sources: []string{
			"https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			"https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1627345011",
		},
	},
	{
		Name:         "27UP850-W",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 27UP850-W by Prototyped (ddcutil 2.0, --i2c-source-addr=x50): switching to DisplayPort with 0xD0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1694629234",
			},
			"hdmi1": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 27UP850-W by Prototyped (ddcutil 2.0, --i2c-source-addr=x50): switching to HDMI 1 with 0x90 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1694629234",
			},
			"hdmi2": {
				mechanism: MechanismLGAltInput,
				value:     0x91,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 27UP850-W by Prototyped (ddcutil 2.0, --i2c-source-addr=x50): switching to HDMI 2 with 0x91 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1694629234",
			},
			"usb-c": {
				mechanism: MechanismLGAltInput,
				value:     0xD1,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 27UP850-W by Prototyped (ddcutil 2.0, --i2c-source-addr=x50): switching to USB-C with 0xD1 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1694629234",
			},
		},
		Notes: []string{
			"Listed on the ddcutil LG wiki page by Prototyped, who published the full table in ddcutil issue #100, taken with ddcutil 2.0 and `--i2c-source-addr=x50`.",
		},
		Sources: []string{
			"https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			"https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1694629234",
		},
	},
	{
		Name:         "27UP85NP-W",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 27UP85NP-W by edror12 (ddcutil): switching to DisplayPort with 0xD0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"usb-c": {
				mechanism: MechanismLGAltInput,
				value:     0xD1,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 27UP85NP-W by edror12 (ddcutil): switching to USB-C with 0xD1 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
		},
		Notes: []string{
			"Test result contributed by edror12 to the ddcutil LG wiki page. Only DisplayPort and USB-C were reported.",
		},
		Sources: []string{
			"https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
		},
	},
	{
		Name:         "27US500-W",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 27US500-W by Fidelxyz (ddcutil): switching to DisplayPort with 0xD0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"hdmi1": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 27US500-W by Fidelxyz (ddcutil): switching to HDMI 1 with 0x90 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"hdmi2": {
				mechanism: MechanismLGAltInput,
				value:     0x91,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 27US500-W by Fidelxyz (ddcutil): switching to HDMI 2 with 0x91 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
		},
		Notes: []string{
			"Test result contributed by Fidelxyz to the ddcutil LG wiki page.",
		},
		Sources: []string{
			"https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
		},
	},
	{
		Name:         "29UM69G",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xC0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 29UM69G by jonpas (ddcutil): switching to DisplayPort with 0xC0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1695779788",
			},
			"hdmi": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 29UM69G by jonpas (ddcutil): switching to HDMI with 0x90 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1695779788",
			},
			"usb-c": {
				mechanism: MechanismLGAltInput,
				value:     0xE0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 29UM69G by jonpas (ddcutil): switching to USB-C with 0xE0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1695779788",
			},
		},
		Notes: []string{
			"One of the two entries whose values are not the usual 0x90/0x91/0xD0/0xD1 set: DisplayPort is 0xC0 and USB-C is 0xE0. The evidence for all three is jonpas' report, on the wiki and in ddcutil issue #100. The same author's `i3/monitor.sh` is listed as corroboration and no more: it defines the USB-C value but only ever invokes the HDMI and DisplayPort ones, so it does not show 0xE0 being sent. That file is not pinned to a commit, because no revision of it has been quoted anywhere this entry could cite.",
			"A single HDMI port is reported, so the input is written bare. A 2016 unit badged 29UM69G-B (EDID `GSM/0x76FA`) did not switch at all, which is recorded here as a warning rather than as a separate entry: there is no schema slot for a negative result. The last source below is that report.",
		},
		Sources: []string{
			"https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			"https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1695779788",
			"https://github.com/jonpas/dotfiles/blob/master/i3/monitor.sh - the same three values; the script defines the USB-C value but only ever invokes the HDMI and DisplayPort ones. Not pinned to a commit: no revision of it has been quoted anywhere this entry could cite",
			"https://github.com/rockowitz/ddcutil/issues/100#issuecomment-2259286211",
		},
	},
	{
		Name:         "29WN600",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 29WN600 by iamSlightlyWind (ddcutil): switching to DisplayPort with 0xD0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"hdmi1": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 29WN600 by iamSlightlyWind (ddcutil): switching to HDMI 1 with 0x90 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"hdmi2": {
				mechanism: MechanismLGAltInput,
				value:     0x91,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 29WN600 by iamSlightlyWind (ddcutil): switching to HDMI 2 with 0x91 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
		},
		Notes: []string{
			"Test result contributed by iamSlightlyWind to the ddcutil LG wiki page.",
		},
		Sources: []string{
			"https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
		},
	},
	{
		Name:         "29U531A",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 29U531A by tinkererkzy (ddcutil): switching to DisplayPort with 0xD0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"hdmi": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 29U531A by tinkererkzy (ddcutil): switching to HDMI with 0x90 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"usb-c": {
				mechanism: MechanismLGAltInput,
				value:     0xD1,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 29U531A by tinkererkzy (ddcutil): switching to USB-C with 0xD1 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
		},
		Notes: []string{
			"Test result contributed by tinkererkzy to the ddcutil LG wiki page. A single HDMI port is reported, so the input is written bare.",
		},
		Sources: []string{
			"https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
		},
	},
	{
		Name:         "32GP750-B",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 32GP750-B by chris-pcguy (ddcutil): switching to DisplayPort with 0xD0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"hdmi1": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 32GP750-B by chris-pcguy (ddcutil): switching to HDMI 1 with 0x90 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"hdmi2": {
				mechanism: MechanismLGAltInput,
				value:     0x91,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 32GP750-B by chris-pcguy (ddcutil): switching to HDMI 2 with 0x91 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
		},
		Notes: []string{
			"Test result contributed by chris-pcguy to the ddcutil LG wiki page.",
		},
		Sources: []string{
			"https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
		},
	},
	{
		Name:         "32GP850-B",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 32GP850-B by erenard (ddcutil): switching to DisplayPort with 0xD0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1925342145",
			},
			"hdmi1": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 32GP850-B by erenard (ddcutil): switching to HDMI 1 with 0x90 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1925342145",
			},
			"hdmi2": {
				mechanism: MechanismLGAltInput,
				value:     0x91,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 32GP850-B by erenard (ddcutil): switching to HDMI 2 with 0x91 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1925342145",
			},
		},
		Notes: []string{
			"Reported working by erenard, on the wiki and in ddcutil issue #100, on a unit manufactured in week 12 of 2023. This one is contested: a later report on the NVapi-write-value-to-monitor tracker describes a 32GP850-B that only flickers and does not change input, and an LG firmware list quoted in ddcutil issue #100 names \"GP850\" as explicitly unsupported. The row stays disabled and without an identity, so nothing is written to either kind of unit; whoever enables it will have to say which firmware they tested.",
		},
		Sources: []string{
			"https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			"https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1925342145",
			"https://github.com/kaleb422/NVapi-write-value-to-monitor/issues/1#issuecomment-2110539219",
			"https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1444483801",
		},
	},
	{
		Name:         "32QN650-B",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 32QN650-B by agspoon (ddcutil): switching to DisplayPort with 0xD0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1626872046",
			},
			"hdmi1": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 32QN650-B by agspoon (ddcutil): switching to HDMI 1 with 0x90 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1626872046",
			},
			"hdmi2": {
				mechanism: MechanismLGAltInput,
				value:     0x91,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 32QN650-B by agspoon (ddcutil): switching to HDMI 2 with 0x91 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1626872046",
			},
		},
		Notes: []string{
			"The wiki row (agspoon) gives no values; the two linked comments on ddcutil issue #100 quote x0090, x0091 and x00d0 for this model.",
		},
		Sources: []string{
			"https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			"https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1626872046",
			"https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1634924423",
		},
	},
	{
		Name:         "32UD99-W",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xE0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 32UD99-W by andrewgodman (Lunar on macOS): switching to DisplayPort with 0xE0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; found by looping over candidate values; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1636997772",
			},
			"hdmi1": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 32UD99-W by andrewgodman (Lunar on macOS): switching to HDMI 1 with 0x90 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1636761366",
			},
			"hdmi2": {
				mechanism: MechanismLGAltInput,
				value:     0x91,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 32UD99-W by andrewgodman (Lunar on macOS): switching to HDMI 2 with 0x91 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1636761366",
			},
			"usb-c": {
				mechanism: MechanismLGAltInput,
				value:     0xC0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 32UD99-W by andrewgodman (Lunar on macOS): switching to USB-C with 0xC0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; found by looping over candidate values; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1636997772",
			},
		},
		Notes: []string{
			"The second entry with unusual values: DisplayPort is 0xE0 and USB-C is 0xC0, the reverse pairing of the 29UM69G. The two comments carry different halves of the result and the rows are cited accordingly: the first one confirms only the HDMI values, and DisplayPort and USB-C appear in the follow-up, where they were found by looping over candidate values with Lunar on macOS. Worth extra care when someone verifies this model on hardware.",
		},
		Sources: []string{
			"https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			"https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1636761366",
			"https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1636997772",
		},
	},
	{
		Name:         "34WN750-B",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 34WN750-B by permezel (ddcutil): switching to DisplayPort with 0xD0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"hdmi1": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 34WN750-B by permezel (ddcutil): switching to HDMI 1 with 0x90 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"hdmi2": {
				mechanism: MechanismLGAltInput,
				value:     0x91,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 34WN750-B by permezel (ddcutil): switching to HDMI 2 with 0x91 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
		},
		Notes: []string{
			"Test result contributed by permezel to the ddcutil LG wiki page.",
		},
		Sources: []string{
			"https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
		},
	},
	{
		Name:         "34WN80C-B",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeQuoted,
				evidence:  "Weaker report on the exact 34WN80C-B by nicklan (a Python USB-HID script, not ddcutil): the report quotes 0xD0 for DisplayPort and says it works, without saying which inputs were tried individually; the wiki entry says only that the script works perfectly and does not quote the values, which come from the linked comment; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1542859752",
			},
			"hdmi1": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeQuoted,
				evidence:  "Weaker report on the exact 34WN80C-B by nicklan (a Python USB-HID script, not ddcutil): the report quotes 0x90 for HDMI 1 and says it works, without saying which inputs were tried individually; the wiki entry says only that the script works perfectly and does not quote the values, which come from the linked comment; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1542859752",
			},
			"hdmi2": {
				mechanism: MechanismLGAltInput,
				value:     0x91,
				grade:     GradeQuoted,
				evidence:  "Weaker report on the exact 34WN80C-B by nicklan (a Python USB-HID script, not ddcutil): the report quotes 0x91 for HDMI 2 and says it works, without saying which inputs were tried individually; the wiki entry says only that the script works perfectly and does not quote the values, which come from the linked comment; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1542859752",
			},
			"usb-c": {
				mechanism: MechanismLGAltInput,
				value:     0xD1,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 34WN80C-B by nicklan (a Python USB-HID script, not ddcutil): switching to USB-C with 0xD1 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; the commenter states that \"0xd1 is actually the usb-c input\" on this monitor; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1542859752",
			},
		},
		Notes: []string{
			"Two evidence strengths in one entry. USB-C is explicit: the linked comment names the input and the value. The other three come from the value table in the referenced gist, which the wiki contributor reports as working without quoting the numbers.",
			"Neither report went through ddcutil. The monitor was driven by the Python USB-HID script in that gist, which is why the evidence strings say so: the mechanism is the same LG side channel, but nothing here says the values survive a `ddcutil setvcp`. The gist is cited unpinned, because no revision of it is quoted in the report.",
		},
		Sources: []string{
			"https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			"https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1542859752",
			"https://gist.github.com/shinyquagsire23/f6b2adef253c6c3ab557a4852bf3abad",
		},
	},
	{
		Name:         "40U990A-W",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 40U990A-W by titou10titou10 (ddcutil): switching to DisplayPort with 0xD0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"hdmi1": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 40U990A-W by titou10titou10 (ddcutil): switching to HDMI 1 with 0x90 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"hdmi2": {
				mechanism: MechanismLGAltInput,
				value:     0x91,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 40U990A-W by titou10titou10 (ddcutil): switching to HDMI 2 with 0x91 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
		},
		Notes: []string{
			"Test result contributed by titou10titou10 to the ddcutil LG wiki page.",
		},
		Sources: []string{
			"https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
		},
	},
	{
		Name:         "40WP95C-W",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 40WP95C-W by fblaese (ddcutil): switching to DisplayPort with 0xD0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"hdmi1": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 40WP95C-W by fblaese (ddcutil): switching to HDMI 1 with 0x90 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"hdmi2": {
				mechanism: MechanismLGAltInput,
				value:     0x91,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 40WP95C-W by fblaese (ddcutil): switching to HDMI 2 with 0x91 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"usb-c": {
				mechanism: MechanismLGAltInput,
				value:     0xD1,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 40WP95C-W by fblaese (ddcutil): switching to USB-C with 0xD1 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
		},
		Notes: []string{
			"Test result contributed by fblaese to the ddcutil LG wiki page.",
		},
		Sources: []string{
			"https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
		},
	},
	{
		Name:         "45GX950A-B",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 45GX950A-B by tyvsmith (ddcutil on Linux): switching to DisplayPort with 0xD0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"hdmi1": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 45GX950A-B by tyvsmith (ddcutil on Linux): switching to HDMI 1 with 0x90 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"hdmi2": {
				mechanism: MechanismLGAltInput,
				value:     0x91,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 45GX950A-B by tyvsmith (ddcutil on Linux): switching to HDMI 2 with 0x91 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			"usb-c": {
				mechanism: MechanismLGAltInput,
				value:     0xD1,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 45GX950A-B by tyvsmith (ddcutil on Linux): switching to USB-C with 0xD1 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
		},
		Notes: []string{
			"The best-corroborated of the new entries: the wiki result, a Stream Deck plugin whose `ddcutil.py` drives these values on Linux, a Windows NVAPI script that copies them from the wiki, and a Windows ADL application whose author says it is \"only tested on 45GX950A-B\".",
			"Two things do not agree. A MonitorControl issue lists read-back values of 15 for USB-C and 209 for DP2, but those are reads through `m1ddc get input-alt`, not writes, so they are not evidence about what a write does. And a BetterDisplay discussion reports a 45GX950A manufactured in week 9 of 2025 that would not leave HDMI 1 by any DDC path on macOS.",
		},
		Sources: []string{
			"https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			"https://github.com/tyvsmith/streamcontroller-lg-monitor-control",
			"https://github.com/meer-cha/lg-input-switch",
			"https://github.com/phillip9933/LGInputSwitch",
			"https://github.com/MonitorControl/MonitorControl/issues/1872",
			"https://github.com/waydabber/BetterDisplay/discussions/5353",
		},
	},
	{
		Name:         "27GP850-B",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 27GP850-B by kaleb422 (Windows, NVAPI): switching to DisplayPort with 0xD0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-2106185595",
			},
			"hdmi1": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 27GP850-B by kaleb422 (Windows, NVAPI): switching to HDMI 1 with 0x90 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-2106185595",
			},
			"hdmi2": {
				mechanism: MechanismLGAltInput,
				value:     0x91,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 27GP850-B by kaleb422 (Windows, NVAPI): switching to HDMI 2 with 0x91 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-2106185595",
			},
		},
		Notes: []string{
			"Same contested family as the 32GP850-B. kaleb422 reports the three values working over NVAPI on Windows and ships them in the NVapi-write-value-to-monitor README, while other owners of GP850 units — including a 27GP850P-B and a unit on firmware 3.06 — see only a flicker, and an LG firmware list names GP850 as unsupported. Recorded, disabled, with the disagreement written down.",
		},
		Sources: []string{
			"https://github.com/rockowitz/ddcutil/issues/100#issuecomment-2106185595",
			"https://github.com/kaleb422/NVapi-write-value-to-monitor",
			"https://github.com/kaleb422/NVapi-write-value-to-monitor/issues/2",
			"https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1695120912",
		},
	},
	{
		Name:         "32UN880-B",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 32UN880-B by two reporters (Windows, NVAPI): switching to DisplayPort with 0xD0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/kaleb422/NVapi-write-value-to-monitor/issues/5#issuecomment-2835626567",
			},
			"hdmi1": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 32UN880-B by two reporters (Windows, NVAPI): switching to HDMI 1 with 0x90 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/kaleb422/NVapi-write-value-to-monitor/issues/5#issuecomment-2835626567",
			},
			"hdmi2": {
				mechanism: MechanismLGAltInput,
				value:     0x91,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 32UN880-B by two reporters (Windows, NVAPI): switching to HDMI 2 with 0x91 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/kaleb422/NVapi-write-value-to-monitor/issues/5#issuecomment-2835626567",
			},
			"usb-c": {
				mechanism: MechanismLGAltInput,
				value:     0xD1,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 32UN880-B by two reporters (Windows, NVAPI): switching to USB-C with 0xD1 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/kaleb422/NVapi-write-value-to-monitor/issues/5#issuecomment-2835626567",
			},
		},
		Notes: []string{
			"Reported independently on the NVapi-write-value-to-monitor tracker (switching from DisplayPort to USB-C, HDMI1, HDMI2 and DP), in ddcutil issue #100, and by way of the amdddc-windows tool in ddcutil issue #612, which uses 0x90.",
			"One quirk is worth repeating to anyone who verifies it: after switching to USB-C, the monitor stopped accepting commands sent from the DisplayPort and HDMI sides.",
		},
		Sources: []string{
			"https://github.com/kaleb422/NVapi-write-value-to-monitor/issues/5#issuecomment-2835626567",
			"https://github.com/kaleb422/NVapi-write-value-to-monitor/issues/8",
			"https://github.com/rockowitz/ddcutil/issues/100#issuecomment-2142184960",
			"https://github.com/rockowitz/ddcutil/issues/612",
		},
	},
	{
		Name:         "34WN780",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeQuoted,
				evidence:  "Weaker report on the exact 34WN780 by piaverous (Windows, NVAPI): the report quotes 0xD0 for DisplayPort and says it works, without saying which inputs were tried individually; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-2453464317",
			},
			"hdmi1": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeQuoted,
				evidence:  "Weaker report on the exact 34WN780 by piaverous (Windows, NVAPI): the report quotes 0x90 for HDMI 1 and says it works, without saying which inputs were tried individually; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-2453464317",
			},
			"hdmi2": {
				mechanism: MechanismLGAltInput,
				value:     0x91,
				grade:     GradeQuoted,
				evidence:  "Weaker report on the exact 34WN780 by piaverous (Windows, NVAPI): the report quotes 0x91 for HDMI 2 and says it works, without saying which inputs were tried individually; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-2453464317",
			},
		},
		Notes: []string{
			"Weaker evidence: the report quotes the three NVAPI values for this model and says \"Worked well\", without saying which it tried.",
		},
		Sources: []string{
			"https://github.com/rockowitz/ddcutil/issues/100#issuecomment-2453464317",
		},
	},
	{
		Name:         "34WN650-W",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeQuoted,
				evidence:  "Weaker report on the exact 34WN650-W by wigust (ddcutil 2.1.2): the report quotes 0xD0 for DisplayPort and says it works, without saying which inputs were tried individually; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1925579750",
			},
			"hdmi1": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeQuoted,
				evidence:  "Weaker report on the exact 34WN650-W by wigust (ddcutil 2.1.2): the report quotes 0x90 for HDMI 1 and says it works, without saying which inputs were tried individually; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1925579750",
			},
			"hdmi2": {
				mechanism: MechanismLGAltInput,
				value:     0x91,
				grade:     GradeQuoted,
				evidence:  "Weaker report on the exact 34WN650-W by wigust (ddcutil 2.1.2): the report quotes 0x91 for HDMI 2 and says it works, without saying which inputs were tried individually; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1925579750",
			},
		},
		Notes: []string{
			"Weaker evidence: the report quotes erenard's three values, says \"Works\" with ddcutil 2.1.2, and does not break the result down per input.",
		},
		Sources: []string{
			"https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1925579750",
		},
	},
	{
		Name:         "28MQ780-B",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 28MQ780-B by amildahl (Windows, ADL): switching to DisplayPort with 0xD0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-2524850195",
			},
			"hdmi1": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 28MQ780-B by amildahl (Windows, ADL): switching to HDMI 1 with 0x90 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-2524850195",
			},
			"hdmi2": {
				mechanism: MechanismLGAltInput,
				value:     0x91,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 28MQ780-B by amildahl (Windows, ADL): switching to HDMI 2 with 0x91 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-2524850195",
			},
		},
		Notes: []string{
			"USB-C is deliberately not recorded. amildahl tested 0xD1, while shinyquagsire23's lg_display_manager — which keys off the model string `28MQ780` — another commenter on that gist with a 28MQ780-B, and a blog write-up all use 0xD2. Two values for one input, on the same model, is exactly the case the catalog refuses to guess at, so the input is left out until somebody tests both.",
		},
		Sources: []string{
			"https://github.com/rockowitz/ddcutil/issues/100#issuecomment-2524850195",
			"https://gist.github.com/shinyquagsire23/f6b2adef253c6c3ab557a4852bf3abad",
		},
	},
	{
		Name:         "32GR93U-B",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 32GR93U-B by gzougianos (Windows, NVAPI): switching to DisplayPort with 0xD0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-2244679727",
			},
			"hdmi1": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 32GR93U-B by gzougianos (Windows, NVAPI): switching to HDMI 1 with 0x90 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-2244679727",
			},
			"hdmi2": {
				mechanism: MechanismLGAltInput,
				value:     0x91,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 32GR93U-B by gzougianos (Windows, NVAPI): switching to HDMI 2 with 0x91 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/issues/100#issuecomment-2244679727",
			},
		},
		Notes: []string{
			"gzougianos reports the \"exact same numbers\" as the NVapi-write-value-to-monitor README working over NVAPI. An m1ddc issue separately reports 208 and 144 working through BetterDisplay's LG alternate input on this model, which is the same two values in decimal.",
		},
		Sources: []string{
			"https://github.com/rockowitz/ddcutil/issues/100#issuecomment-2244679727",
			"https://github.com/waydabber/m1ddc/issues/48",
		},
	},
	{
		Name:         "32GP83B",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 32GP83B by Gilgame24 (ddcutil): switching to DisplayPort with 0xD0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/discussions/331#discussioncomment-16088333",
			},
			"hdmi1": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 32GP83B by Gilgame24 (ddcutil): switching to HDMI 1 with 0x90 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/discussions/331#discussioncomment-16088333",
			},
			"hdmi2": {
				mechanism: MechanismLGAltInput,
				value:     0x91,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 32GP83B by Gilgame24 (ddcutil): switching to HDMI 2 with 0x91 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/rockowitz/ddcutil/discussions/331#discussioncomment-16088333",
			},
		},
		Notes: []string{
			"Reported by Gilgame24 in ddcutil discussion 331.",
		},
		Sources: []string{
			"https://github.com/rockowitz/ddcutil/discussions/331#discussioncomment-16088333",
		},
	},
	{
		Name:         "34U650A-B",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 34U650A-B by mikecarlton (BetterDisplay on macOS): switching to DisplayPort with 0xD0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/waydabber/BetterDisplay/issues/4853",
			},
			"hdmi1": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 34U650A-B by mikecarlton (BetterDisplay on macOS): switching to HDMI 1 with 0x90 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/waydabber/BetterDisplay/issues/4853",
			},
			"hdmi2": {
				mechanism: MechanismLGAltInput,
				value:     0x91,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 34U650A-B by mikecarlton (BetterDisplay on macOS): switching to HDMI 2 with 0x91 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/waydabber/BetterDisplay/issues/4853",
			},
			"usb-c": {
				mechanism: MechanismLGAltInput,
				value:     0x1D1,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 34U650A-B by mikecarlton (BetterDisplay ddcAlt, macOS): switching to USB-C with 0x1D1 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; found by looping over values; the listed 0xD2 got no response; 0x1D1 is 465 decimal; not verified here: https://github.com/waydabber/BetterDisplay/issues/4853",
			},
		},
		Notes: []string{
			"The report gives the values in decimal — ddcAlt 144, 145 and 208 \"work correctly\". The USB-C value is the one entry in the catalog that does not fit in a byte: 210 got no response, and 465 did.",
		},
		Sources: []string{
			"https://github.com/waydabber/BetterDisplay/issues/4853",
			"https://github.com/waydabber/BetterDisplay/discussions/4883",
		},
	},
	{
		Name:         "40WP95X",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"usb-c": {
				mechanism: MechanismLGAltInput,
				value:     0xD1,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 40WP95X by stepahin (Windows, NVAPI): switching to USB-C with 0xD1 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/kaleb422/NVapi-write-value-to-monitor/issues/5",
			},
		},
		Notes: []string{
			"Only USB-C is reported: \"This is how switching to USB-C input works\".",
		},
		Sources: []string{
			"https://github.com/kaleb422/NVapi-write-value-to-monitor/issues/5",
		},
	},
	{
		Name:         "34GS95QE",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 34GS95QE by Vib0 (Windows, NVAPI): switching to DisplayPort with 0xD0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/kaleb422/NVapi-write-value-to-monitor/issues/5#issuecomment-2812426302",
			},
			"hdmi1": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 34GS95QE by Vib0 (Windows, NVAPI): switching to HDMI 1 with 0x90 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/kaleb422/NVapi-write-value-to-monitor/issues/5#issuecomment-2812426302",
			},
			"hdmi2": {
				mechanism: MechanismLGAltInput,
				value:     0x91,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 34GS95QE by Vib0 (Windows, NVAPI): switching to HDMI 2 with 0x91 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/kaleb422/NVapi-write-value-to-monitor/issues/5#issuecomment-2812426302",
			},
		},
		Notes: []string{
			"Vib0 reports the three values as \"Tested\". A BetterDisplay discussion separately shows a 34GS95QE-B working through the LG alternate input, but the values there appear only in a screenshot, so that report corroborates the mechanism rather than the numbers.",
		},
		Sources: []string{
			"https://github.com/kaleb422/NVapi-write-value-to-monitor/issues/5#issuecomment-2812426302",
			"https://github.com/waydabber/BetterDisplay/discussions/4246",
		},
	},
	{
		Name:         "32UP83AK-W",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeReported,
				evidence:  "Reported working on the exact 32UP83AK-W by 5uck1ess (Windows, NVAPI): switching to DisplayPort with 0xD0 over the LG side channel (source address 0x50, VCP 0xF4) succeeded; not verified here: https://github.com/kaleb422/NVapi-write-value-to-monitor/issues/2#issuecomment-3221830027",
			},
		},
		Notes: []string{
			"The reporter says 0xD0 \"works without any issues\" and that they switch to HDMI and DisplayPort, but never writes the HDMI value down, so only DisplayPort is recorded.",
		},
		Sources: []string{
			"https://github.com/kaleb422/NVapi-write-value-to-monitor/issues/2#issuecomment-3221830027",
			"https://github.com/kaleb422/NVapi-write-value-to-monitor/issues/3#issuecomment-3224103812",
		},
	},
	{
		Name:         "32BL95U-W",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeDocumented,
				evidence:  "Documented by LG for the exact 32BL95U-W: DisplayPort is 0xD0 over the LG side channel (source address 0x50, VCP 0xF4); no field report; the service manual's Screen adjust command table, row 13, maps Input Select, command F4, to this value; not verified here: https://research.encompass.com/ZEN/sm/32BL95UW.pdf",
			},
			"hdmi1": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeDocumented,
				evidence:  "Documented by LG for the exact 32BL95U-W: HDMI 1 is 0x90 over the LG side channel (source address 0x50, VCP 0xF4); no field report; the service manual's Screen adjust command table, row 13, maps Input Select, command F4, to this value; not verified here: https://research.encompass.com/ZEN/sm/32BL95UW.pdf",
			},
			"thunderbolt": {
				mechanism: MechanismLGAltInput,
				value:     0xD2,
				grade:     GradeDocumented,
				evidence:  "Documented by LG for the exact 32BL95U-W: Thunderbolt is 0xD2 over the LG side channel (source address 0x50, VCP 0xF4); no field report; the service manual's Screen adjust command table, row 13, maps Input Select, command F4, to this value; not verified here: https://research.encompass.com/ZEN/sm/32BL95UW.pdf",
			},
		},
		Notes: []string{
			"The one entry documented by the manufacturer rather than by a user. The service manual's cover says `MODEL : 32BL95U`; the marketed name with its suffix is established by cross-reference, from the manual's file name `32BL95UW.pdf` and LG's own product page, which lists `32BL95U-W.AUB` as the only 32BL95U variant. Thunderbolt is the first use of that connector kind in the catalog.",
			"The EDID product IDs the manual assigns — 0x7706 for HDMI, 0x7707 for DisplayPort, 0x7722 for Thunderbolt, model name `LG HDR 4K` — are not recorded as identities, because a model that is not write-enabled must record none; they would also collide with other LG models, which is discussed at the end of this page.",
			"The spec table's `User Model Name 32UL950` gets no entry of its own and no merge: an alias in a manual is not a report that a 32UL950 switches inputs.",
		},
		Sources: []string{
			"https://research.encompass.com/ZEN/sm/32BL95UW.pdf",
			"https://www.lg.com/us/support/product/lg-32BL95U-W",
			"https://github.com/rockowitz/ddcutil/issues/100#issuecomment-1435477786",
		},
	},
	{
		Name:         "32U990A",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			"dp": {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				grade:     GradeQuoted,
				evidence:  "Weaker report on the exact 32U990A by pyang2045 (m1ddc input-alt on macOS): the report quotes 0xD0 for DisplayPort and says it works, without saying which inputs were tried individually; not verified here: https://github.com/pyang2045/streamdeck-display-knob",
			},
			"hdmi": {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				grade:     GradeQuoted,
				evidence:  "Weaker report on the exact 32U990A by pyang2045 (m1ddc input-alt on macOS): the report quotes 0x90 for HDMI and says it works, without saying which inputs were tried individually; not verified here: https://github.com/pyang2045/streamdeck-display-knob",
			},
			"thunderbolt": {
				mechanism: MechanismLGAltInput,
				value:     0xD2,
				grade:     GradeQuoted,
				evidence:  "Weaker report on the exact 32U990A by pyang2045 (m1ddc input-alt on macOS): the report quotes 0xD2 for Thunderbolt and says it works, without saying which inputs were tried individually; not verified here: https://github.com/pyang2045/streamdeck-display-knob",
			},
		},
		Notes: []string{
			"The weakest entry here. `lg.sh` in pyang2045/streamdeck-display-knob is described as \"Manual control of the LG UltraFine 32U990A\" and sends m1ddc `input-alt` 144, 208 and 210, but the script does not say whether it was run successfully. A single HDMI port is reported, so the input is written bare.",
		},
		Sources: []string{
			"https://github.com/pyang2045/streamdeck-display-knob",
		},
	},
}
