/*
 * Copyright 2026 Roberto Leinardi.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by internal/catalog/internal/generate from models.yaml; DO NOT EDIT.

package catalog

// models is the supported-monitor catalog. It is rendered from models.yaml,
// which is the file to edit; run `make go-generate` afterwards. A test fails
// the build if this file and models.yaml disagree.
var models = []Model{
	{
		Name:   "38WR85QC-W",
		Vendor: "LG",
		Identities: []Identity{
			{Manufacturer: "GSM", ProductCode: 0x77D3},
			{Manufacturer: "GSM", ProductCode: 0x77D4},
		},
		WriteEnabled: true,
		Inputs: map[Input]inputOp{
			InputDP: {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				evidence:  "Direct test on the unit, 2026-09-07, Linux (ddcutil) and macOS (m1ddc): switched from USB-C to DisplayPort",
			},
			InputUSBC: {
				mechanism: MechanismLGAltInput,
				value:     0xD1,
				evidence:  "Direct test on the unit, 2026-09-07, Linux (ddcutil) and macOS (m1ddc): switched from DisplayPort to USB-C",
			},
		},
		Sources: []string{
			"Direct observation on the tested unit: EDID GSM/0x77D3 (DisplayPort) and GSM/0x77D4 (USB-C), model string LG ULTRAWIDE",
			"https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
		},
	},
	{
		Name:         "38BR85QC",
		Vendor:       "LG",
		Identities:   nil,
		WriteEnabled: false,
		Inputs: map[Input]inputOp{
			InputDP: {
				mechanism: MechanismLGAltInput,
				value:     0xD0,
				evidence:  "Reported by a tester on the ddcutil LG wiki page; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			InputUSBC: {
				mechanism: MechanismLGAltInput,
				value:     0xD1,
				evidence:  "Reported by a tester on the ddcutil LG wiki page; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			InputHDMI1: {
				mechanism: MechanismLGAltInput,
				value:     0x90,
				evidence:  "Reported by a tester on the ddcutil LG wiki page; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
			InputHDMI2: {
				mechanism: MechanismLGAltInput,
				value:     0x91,
				evidence:  "Reported by a tester on the ddcutil LG wiki page; not verified here: https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
			},
		},
		Sources: []string{
			"https://github.com/rockowitz/ddcutil/wiki/Switching-input-source-on-LG-monitors",
		},
	},
}
